services:
  - type: web
    name: r8raihan-bot        # আপনার অ্যাপের নাম
    runtime: php              # এটি একটি PHP প্রজেক্ট
    plan: free                # ফ্রি প্ল্যান ব্যবহার করা হবে
    buildCommand: composer install
    startCommand: php -S 0.0.0.0:$PORT index.php
    envVars:
      - key: PHP_VERSION
        value: 8.2
